version: '3'
services:
  app:
    build:
      context: https://github.com/ryebreadgit/CreatorSpace.git
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /downloads:/path/to/downloads
      - /settings.json:/path/to/appdata/CreatorSpace/settings.json
      - /database.db:/path/to/appdata/CreatorSpace/database.db # optional for sqlite
    environment:
          - GIN_MODE=release